### ISSUE TITLE
Unable to login in localhost 

### ISSUE THREAD

**Issue by PiyushThapaa** [fossasia/open-event-checkin#112]
After running `npm run dev`, I'm unable to login in localhost (email and password are correct)...

![Screenshot 2024-02-24 184947](https://github.com/fossasia/open-event-checkin/assets/112943430/1f2b80e5-729b-4de2-b1c1-dcf9142e6179)

**Comment by AviGawande** [comment]
hey @PiyushThapaa did you  got the issue while logging in, by the way i am also having the same one.

**Comment by PiyushThapaa** [comment]
@AviGawande Still not able to login

**Comment by mschandana16** [comment]
@AviGawande and @PiyushThapaa 
even I'm facing the same issue

**Comment by cweitat** [comment]
@AviGawande @PiyushThapaa @mschandana16 did you have an account created on eventyay? do you have any events created?

**Comment by AviGawande** [comment]
Actually I had setup the Eventyay project locally and also created the account on the Eventyay.

**Comment by PiyushThapaa** [comment]
@cweitat This issue is now resolved from my side...

**Comment by cweitat** [comment]
> Actually I had setup the Eventyay project locally and also created the account on the Eventyay.

local host is using the test version of eventyay, not the production

**Comment by AviGawande** [comment]
@PiyushThapaa did you setup the Eventyay-tickets locally means i am  having problem in it.could you please help me out in this.

**Comment by PiyushThapaa** [comment]
@AviGawande We just have to make account in `test.eventyay.com` because localhost is linked with test version of eventyay and not with the actual one
